ccflags-y += -DRFFS_TRACE -DRFFS_DEBUG
KSRC = /usr/src/linux-source-3.0.0

obj-m += rffs.o
rffs-objs := inode.o file.o rffs_file.o log.o

default:
	$(MAKE) -C $(KSRC) SUBDIRS=`pwd` modules

clean:
	$(MAKE) -C $(KSRC) SUBDIRS=`pwd` clean
