ccflags-y += -Wno-implicit-function-declaration
KSRC = /usr/src/linux-source-3.0.0

obj-m += rffs.o
rffs-objs := file.o inode.o log.o

default:
	$(MAKE) -C $(KSRC) SUBDIRS=`pwd` modules

clean:
	$(MAKE) -C $(KSRC) SUBDIRS=`pwd` clean
