CC = gcc
CCC = arm-none-linux-gnueabi-gcc # to cross-compile
CFLAGS += -Wall # -g
LIB = -lpthread
HEADERS = ada_log.h ada_sys.h ulist.h uatomic.h

all : test-sort test-trace

test-sort : ada_log.c test-sort.c $(HEADERS)
	$(CC) $(CFLAGS) -pthread $(LIB) -o $@.out $^

test-trace : test-trace.c
	$(CCC) $(CFLAGS) -static -march=armv7-a -o $@.o $^

clean :
	rm -rf *.out
