CC = gcc
CCC = arm-none-linux-gnueabi-gcc # to cross-compile
CFLAGS += -Wall # -g
LIB = -lpthread
HEADERS = ada_log.h ada_sys.h ulist.h uatomic.h

all : test-sort

test-sort : ada_log.c test-sort.c $(HEADERS)
	$(CC) $(CFLAGS) -pthread $(LIB) -o $@.out $^
clean :
	rm -rf *.out
