ccflags-y += -DADA_DEBUG
KSRC = /usr/src/linux-source-3.0.31

obj-m += adafs.o
adafs-objs := inode.o file.o ada_file.o ada_log.o

default:
	$(MAKE) -C $(KSRC) SUBDIRS=`pwd` modules

clean:
	$(MAKE) -C $(KSRC) SUBDIRS=`pwd` clean
